### ISSUE TITLE
Backend ssl/tls support

### ISSUE THREAD

**Issue by mokhtarabadi** [genshen/wssocks#11]
I trying to import generated SSL into server-side and I can't so I decided to put Nginx as a proxy server and put SSL into it, but when I use wss://server:443 I see bad handshake error in client-side, what is the problem and how I can put an SSL proxy middle of the connection?

**Comment by mokhtarabadi** [comment]
@genshen what news about this feature?

**Comment by genshen** [comment]
Hi @mokhtarabadi , with the release of wssocks v0.5.0, you can enable backend SSL now.  
Currently, this feature is only supported by nginx by putting SSL into nginx config.  

Latter, I plan to add feature of ssl/tls support to wssocks itself (ssl/tls support even if there is no nginx). And PR is welcome if you have good idea😜😜.

e.g:
1. config nginx
```nginx
server {
listen         80;
listen [::]:80;
server_name     proxy.example.com;
return          301 https://$http_host$request_uri;
}

server {
listen     0.0.0.0:443 ssl;
listen     [::]:443 ssl;
server_name  proxy.example.com;
access_log   logs/proxy.example.com.access.log;
ssl_certificate      ../sslcrt/proxy.example.com/proxy.example.com.crt; # or .cer file
ssl_certificate_key  ../sslcrt/proxy.example.com/proxy.example.com.key;

location / {
client_max_body_size 1024m;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header Host            $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;   # wssocks v0.5.0 require HTTP 1.1 at least
proxy_pass http://127.0.0.1:10000;
}
}
```
2. launch wssocks server
```bash
./wssocks-linux-amd64 server --status --addr :10000
# or launch server via docker
```

3. At client side:
```bash
./wssocks-darwin-amd64 client --remote wss://proxy.example.com
```
If your certificate is self-signed, you can set `--skip-tls-verify` option when launching client.

4. Enjoy it
```bash
# on Mac
ssh -o ProxyCommand='nc -x 127.0.0.1:1080 %h %p' gpu_node

env GIT_SSH_COMMAND="ssh -o ProxyCommand='nc -x 127.0.0.1:1080 %h %p' " git clone git@github.com:genshen/wssocks.git
```

**Comment by genshen** [comment]
As far as I know, this approach (ssl with nginx) is also supported before version 0.5.0 (e.g. I have tested v0.4.1, it also works fine).   

In v0.5.0, feature of **automatic redirect** is added.  
For example, if ssl/tls at server side is enabled by nginx with above nginx config, we can connect to server by both address `wss://proxy.example.com` and `ws://proxy.example.com` in v0.5.0 (the later one will be redirected to the former one automatically).    
While the address `ws://proxy.example.com` is not supported in v0.4.x (it will raise an error `establishing connection error:websocket: bad handshake`).

**Comment by mokhtarabadi** [comment]
Hey @genshen 
Thank you so much
I just check the TLS support now with the latest version, and everything works great 
unfortunately, I don't know go language so I can't help you with PR (I'm java & android developer)

I used haproxy as load balancer and inject TLS into that and for client use wss:// as the protocol
