### ISSUE TITLE
multi-threading

### ISSUE THREAD

**Issue by DefinitlyEvil** [genshen/wssocks#3]
hi, 
This is a awesome tool, however I found that it is single-threaded. 
For example, I couldn't open a web page when downloading a file... 

thanks, 
Tobias.

**Comment by mokhtarabadi** [comment]
+1

**Comment by mokhtarabadi** [comment]
@genshen This is really a great project, the only problem I found that's about single threaded, please try to change to muti threading, thanks

**Comment by mokhtarabadi** [comment]
For example when I using wssocks in termux and set proxy for telegram, first time is great but when I try to download a video for example, other things not work mean downloading images or even new messages

**Comment by genshen** [comment]
Hi @mokhtarabadi,  really really thanks for your support and feedback.  
This problem may have been fix in latest version (v0.4.1).  
I have tested wssocks v0.4.1 on both Mac and Linux with three downloads (dl.google.com) and one https request (send.firefox.com).  
The four connections can run concurrent on both Mac and Linux.  

Perhaps you can update to latest version and check whether it solve this problem.  
Feel free to reply this issue if you have any progress.  

![screen-record-2020-07-09](https://user-images.githubusercontent.com/11265498/86953749-6eb01280-c187-11ea-8c20-f6612bf06d14.gif)

**Comment by mokhtarabadi** [comment]
Thanks so much ❤️, I will test tomorrow

**Comment by mokhtarabadi** [comment]
Now works like a charm, thanks
