### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by segator** [genshen/wssocks#31]
client and server docker support it will be nice

**Comment by genshen** [comment]
Hi, docker is supported. You can pull docker image from https://hub.docker.com/repository/docker/genshen/wssocks/.
e.g.
```bash
docker pull genshen/wssocks:0.5.0
# server
docker run --rm genshen/wssocks:0.5.0 server --addr :1088
# client
docker run --rm genshen/wssocks:0.5.0 client --remote was://example.com:1088
```

You can also build you own docker image from [Dockerfile](../blob/master/Dockerfile) in this repo.
