### ISSUE TITLE
Connection error on Windows

### ISSUE THREAD

**Issue by jeevank** [genshen/wssocks#39]
I have wssocks server setup on Linux behind nginx as found in the readme here.

When I run the client on an Ubuntu desktop, the socks proxy works great.

However the exact same command for the client on Windows 11  (using the binary release) gives the following error:

```
wssocks.exe client --remote "wss://subdomain.server.com"
time="2021-07-13T22:57:40-04:00" level=info msg="http(s) proxy is disabled."
time="2021-07-13T22:57:40-04:00" level=info msg="connecting to wssocks server." remote="wss://subdomain.server.com"
time="2021-07-13T22:57:40-04:00" level=fatal msg="establishing connection error: failed to WebSocket dial: failed to send handshake request: Get \"https://subdomain.server.com\": dial tcp 123.123.123.123:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```

(I've changed the `remote` address and IPs above from the real one)

I've tried a few variations of the command above (like using `--skip-tls-verify` flag, specifying different `--addr` values and such) but I get the same error message. Again, this same command works great works when I use Ubuntu linux to run my client.

I'm using the pre-built binaries from the latest release (0.5.0) for both the server and client.

**Comment by genshen** [comment]
😊

**Comment by jeevank** [comment]
Just tested client in Mac as well and its working great. Love the single-binary cross-platform magic!
