### ISSUE TITLE
authentication mechanism

### ISSUE THREAD

**Issue by DefinitlyEvil** [genshen/wssocks#4]
I think it will be wonderful if clients can be authenticated, you can check out my fork, I used HTTP header to validate the key. ;)

**Comment by genshen** [comment]
Thanks for your good suggestion, PR is welcome!

**Comment by DefinitlyEvil** [comment]
I already implemented this in my fork but I gotta change a lot of import stuffs and namespaces... ;)

**Comment by genshen** [comment]
close it now, see PR #8
